name: æ‰¹é‡æž„å»º Magisk æ¨¡å—

on:
  workflow_dispatch:

jobs:
  batch-build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ å…‹éš†ä»“åº“
        uses: actions/checkout@v3

      - name: ðŸ›  å®‰è£…ä¾èµ–
        run: |
          sudo apt update
          sudo apt-get install -y aria2 zip unzip

      - name: ðŸš€ æ‰§è¡Œæ‰¹é‡æž„å»º
        run: |
          bash ./batch_build.sh

      - name: â° èŽ·å–å½“å‰æ—¶é—´
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: ðŸ“¦ ä¸Šä¼ æ‰€æœ‰æž„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4
        with:
          name: batch-build-artifacts-${{ github.run_id }}-${{ steps.datetime.outputs.datetime }}
          path: batch_dist/
