name: æ‰¹é‡æž„å»º Magisk æ¨¡å—

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ðŸ§¾ æ£€å‡º batch_rom_list.json
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: |
            batch_rom_list.json
          sparse-checkout-cone-mode: false
      - name: ðŸš€ ç”Ÿæˆå¹¶å‘çŸ©é˜µ
        id: set-matrix
        run: |
          jq -c '
            to_entries
            | map(
                .key as $device
                | .value
                | map({
                    device: $device,
                    rom: .rom,
                  })
              )
            | flatten
            | {include: .}
          ' batch_rom_list.json >matrix.json
          echo "matrix=$(cat matrix.json | jq -c .)" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: ðŸ§¾ å…‹éš†ä»“åº“
        uses: actions/checkout@v4.2.2

      - name: ðŸ›  å®‰è£…ä¾èµ–
        run: |
          sudo apt update
          sudo apt-get install -y zip unzip

      - name: ðŸš€ æ‰§è¡Œæ‰¹é‡æž„å»º
        run: |
          url=$(jq -r --arg device "${{ matrix.device }}" --arg rom "${{ matrix.rom }}" '
            .[$device][] | select(.rom == $rom) | .url' batch_rom_list.json)
          bash ./build.sh --rom "${{ matrix.rom }}" \
                          --url "$url"
      - name: ðŸ“¦ ä¸Šä¼ æž„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "${{ matrix.device }}-${{ matrix.rom }}"
          path: tmp/release/

  merge-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: â¬‡ï¸ ä¸‹è½½æ‰€æœ‰æž„å»ºäº§ç‰©
        uses: actions/download-artifact@v5.0.0
        with:
          path: combined-artifacts

      - name: â° èŽ·å–å½“å‰æ—¶é—´
        id: datetime
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: ðŸ“¦ å¤„ç†æ€»æž„å»ºäº§ç‰©
        run: |
          cd combined-artifacts
          find . -mindepth 1 -maxdepth 1 -type d | while IFS= read -r dir; do
              dirname="${dir#./}"
              model="${dirname%%-*}"
              version="${dirname#*-}"
              if [[ "$model" == "$dirname" || "$version" == "$dirname" ]]; then
                  continue
              fi
              mkdir -p "$model"
              cd "$dirname"
              zip -r "../$model/${version}.zip" . >/dev/null
              cd ..
              rm -rf "$dirname"
          done

      - name: ðŸ“¦ ä¸Šä¼ æ€»æž„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4.6.2
        with:
          name: batch-build-artifacts-${{ github.run_id }}-${{ steps.datetime.outputs.datetime }}
          path: combined-artifacts/
