name: æ‰¹é‡æ„å»º Magisk æ¨¡å—

on:
  workflow_dispatch:

jobs:
  batch-build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ å…‹éš†ä»“åº“
        uses: actions/checkout@v3

      - name: ğŸ›  å®‰è£…ä¾èµ–
        run: |
          sudo apt update
          sudo apt install -y zip unzip python3-pip
          pip install --user pipx
          pipx ensurepath
          pipx install git+https://github.com/5ec1cff/payload-dumper

      - name: ğŸš€ æ‰§è¡Œæ‰¹é‡æ„å»º
        run: |
          bash ./batch_build.sh

      - name: ğŸ“¦ ä¸Šä¼ æ‰€æœ‰æ„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4
        with:
            name: batch-build-artifacts-${{ github.run_id }}-$(date +%Y-%m-%d-%H-%M)
            path: batch_dist/
