name: æ„å»º Magisk æ¨¡å—

on:
  workflow_dispatch:
    inputs:
      rom:
        description: 'ROM ç‰ˆæœ¬å· (e.g., OS2.0.202.0.VOZCNXM)'
        required: true
      url:
        description: 'ROM ä¸‹è½½é“¾æ¥'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ å…‹éš†ä»“åº“
        uses: actions/checkout@v4.2.2

      - name: ğŸ›  å®‰è£…ä¾èµ–
        run: |
          sudo apt update
          sudo apt-get install -y zip unzip

      - name: ğŸ§ª æ„å»ºæ¨¡å—
        run: |
          bash ./build.sh --rom "${{ github.event.inputs.rom }}" \
                          --url "${{ github.event.inputs.url }}"

      - name: ğŸ“¦ ä¸Šä¼ æ„å»ºäº§ç‰©
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "${{ github.event.inputs.rom }}"
          path: tmp/release/
